# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  syntax='proto3',
  serialized_options=_b('\n\025io.grpc.examples.chatB\tChatProtoP\001\242\002\001C'),
  serialized_pb=_b('\n\nchat.proto\x12\x04\x63hat\"\x13\n\x04Info\x12\x0b\n\x03Msg\x18\x01 \x01(\t\"N\n\x08Mensajes\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02\x64\x65\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x05 \x01(\t\"(\n\x08RCliente\x12\x0f\n\x07usuario\x18\x02 \x01(\t\x12\x0b\n\x03pas\x18\x03 \x01(\t\"4\n\x08LCliente\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07usuario\x18\x02 \x01(\t\x12\x0b\n\x03pas\x18\x03 \x01(\t\"%\n\x07\x43liente\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06Nombre\x18\x02 \x01(\t\"\x17\n\tidCliente\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\tLMensajes\x12\n\n\x02\x64\x65\x18\x01 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x02 \x01(\t\x12\x0f\n\x07mensaje\x18\x03 \x01(\t2\xd1\x02\n\x04\x43hat\x12\x33\n\x0fListadoClientes\x12\r.chat.Cliente\x1a\r.chat.Cliente\"\x00\x30\x01\x12\x35\n\x0fListadoMensajes\x12\r.chat.Cliente\x1a\x0f.chat.LMensajes\"\x00\x30\x01\x12\x36\n\x10ListadoMensajes2\x12\r.chat.Cliente\x1a\x0f.chat.LMensajes\"\x00\x30\x01\x12%\n\x05Login\x12\x0e.chat.RCliente\x1a\n.chat.Info\"\x00\x12(\n\x08Registro\x12\x0e.chat.RCliente\x1a\n.chat.Info\"\x00\x12$\n\x04Send\x12\x0e.chat.Mensajes\x1a\n.chat.Info\"\x00\x12.\n\nGetCliente\x12\x0f.chat.idCliente\x1a\r.chat.Cliente\"\x00\x42(\n\x15io.grpc.examples.chatB\tChatProtoP\x01\xa2\x02\x01\x43\x62\x06proto3')
)




_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='chat.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Msg', full_name='chat.Info.Msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=39,
)


_MENSAJES = _descriptor.Descriptor(
  name='Mensajes',
  full_name='chat.Mensajes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.Mensajes.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='de', full_name='chat.Mensajes.de', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='chat.Mensajes.to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='chat.Mensajes.mensaje', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fecha', full_name='chat.Mensajes.fecha', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=119,
)


_RCLIENTE = _descriptor.Descriptor(
  name='RCliente',
  full_name='chat.RCliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='chat.RCliente.usuario', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pas', full_name='chat.RCliente.pas', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=161,
)


_LCLIENTE = _descriptor.Descriptor(
  name='LCliente',
  full_name='chat.LCliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.LCliente.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usuario', full_name='chat.LCliente.usuario', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pas', full_name='chat.LCliente.pas', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=215,
)


_CLIENTE = _descriptor.Descriptor(
  name='Cliente',
  full_name='chat.Cliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.Cliente.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Nombre', full_name='chat.Cliente.Nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=254,
)


_IDCLIENTE = _descriptor.Descriptor(
  name='idCliente',
  full_name='chat.idCliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.idCliente.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=279,
)


_LMENSAJES = _descriptor.Descriptor(
  name='LMensajes',
  full_name='chat.LMensajes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='de', full_name='chat.LMensajes.de', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fecha', full_name='chat.LMensajes.fecha', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='chat.LMensajes.mensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=336,
)

DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['Mensajes'] = _MENSAJES
DESCRIPTOR.message_types_by_name['RCliente'] = _RCLIENTE
DESCRIPTOR.message_types_by_name['LCliente'] = _LCLIENTE
DESCRIPTOR.message_types_by_name['Cliente'] = _CLIENTE
DESCRIPTOR.message_types_by_name['idCliente'] = _IDCLIENTE
DESCRIPTOR.message_types_by_name['LMensajes'] = _LMENSAJES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Info)
  })
_sym_db.RegisterMessage(Info)

Mensajes = _reflection.GeneratedProtocolMessageType('Mensajes', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJES,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Mensajes)
  })
_sym_db.RegisterMessage(Mensajes)

RCliente = _reflection.GeneratedProtocolMessageType('RCliente', (_message.Message,), {
  'DESCRIPTOR' : _RCLIENTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.RCliente)
  })
_sym_db.RegisterMessage(RCliente)

LCliente = _reflection.GeneratedProtocolMessageType('LCliente', (_message.Message,), {
  'DESCRIPTOR' : _LCLIENTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LCliente)
  })
_sym_db.RegisterMessage(LCliente)

Cliente = _reflection.GeneratedProtocolMessageType('Cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Cliente)
  })
_sym_db.RegisterMessage(Cliente)

idCliente = _reflection.GeneratedProtocolMessageType('idCliente', (_message.Message,), {
  'DESCRIPTOR' : _IDCLIENTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.idCliente)
  })
_sym_db.RegisterMessage(idCliente)

LMensajes = _reflection.GeneratedProtocolMessageType('LMensajes', (_message.Message,), {
  'DESCRIPTOR' : _LMENSAJES,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LMensajes)
  })
_sym_db.RegisterMessage(LMensajes)


DESCRIPTOR._options = None

_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='chat.Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=339,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListadoClientes',
    full_name='chat.Chat.ListadoClientes',
    index=0,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_CLIENTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListadoMensajes',
    full_name='chat.Chat.ListadoMensajes',
    index=1,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_LMENSAJES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListadoMensajes2',
    full_name='chat.Chat.ListadoMensajes2',
    index=2,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_LMENSAJES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='chat.Chat.Login',
    index=3,
    containing_service=None,
    input_type=_RCLIENTE,
    output_type=_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Registro',
    full_name='chat.Chat.Registro',
    index=4,
    containing_service=None,
    input_type=_RCLIENTE,
    output_type=_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='chat.Chat.Send',
    index=5,
    containing_service=None,
    input_type=_MENSAJES,
    output_type=_INFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCliente',
    full_name='chat.Chat.GetCliente',
    index=6,
    containing_service=None,
    input_type=_IDCLIENTE,
    output_type=_CLIENTE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
