# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListadoClientes = channel.unary_stream(
        '/chat.Chat/ListadoClientes',
        request_serializer=chat__pb2.Cliente.SerializeToString,
        response_deserializer=chat__pb2.Cliente.FromString,
        )
    self.ListadoMensajes = channel.unary_stream(
        '/chat.Chat/ListadoMensajes',
        request_serializer=chat__pb2.Cliente.SerializeToString,
        response_deserializer=chat__pb2.LMensajes.FromString,
        )
    self.ListadoMensajes2 = channel.unary_stream(
        '/chat.Chat/ListadoMensajes2',
        request_serializer=chat__pb2.Cliente.SerializeToString,
        response_deserializer=chat__pb2.LMensajes.FromString,
        )
    self.Login = channel.unary_unary(
        '/chat.Chat/Login',
        request_serializer=chat__pb2.RCliente.SerializeToString,
        response_deserializer=chat__pb2.Info.FromString,
        )
    self.Registro = channel.unary_unary(
        '/chat.Chat/Registro',
        request_serializer=chat__pb2.RCliente.SerializeToString,
        response_deserializer=chat__pb2.Info.FromString,
        )
    self.Send = channel.unary_unary(
        '/chat.Chat/Send',
        request_serializer=chat__pb2.Mensajes.SerializeToString,
        response_deserializer=chat__pb2.Info.FromString,
        )
    self.GetCliente = channel.unary_unary(
        '/chat.Chat/GetCliente',
        request_serializer=chat__pb2.idCliente.SerializeToString,
        response_deserializer=chat__pb2.Cliente.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListadoClientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListadoMensajes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListadoMensajes2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Registro(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCliente(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListadoClientes': grpc.unary_stream_rpc_method_handler(
          servicer.ListadoClientes,
          request_deserializer=chat__pb2.Cliente.FromString,
          response_serializer=chat__pb2.Cliente.SerializeToString,
      ),
      'ListadoMensajes': grpc.unary_stream_rpc_method_handler(
          servicer.ListadoMensajes,
          request_deserializer=chat__pb2.Cliente.FromString,
          response_serializer=chat__pb2.LMensajes.SerializeToString,
      ),
      'ListadoMensajes2': grpc.unary_stream_rpc_method_handler(
          servicer.ListadoMensajes2,
          request_deserializer=chat__pb2.Cliente.FromString,
          response_serializer=chat__pb2.LMensajes.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=chat__pb2.RCliente.FromString,
          response_serializer=chat__pb2.Info.SerializeToString,
      ),
      'Registro': grpc.unary_unary_rpc_method_handler(
          servicer.Registro,
          request_deserializer=chat__pb2.RCliente.FromString,
          response_serializer=chat__pb2.Info.SerializeToString,
      ),
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=chat__pb2.Mensajes.FromString,
          response_serializer=chat__pb2.Info.SerializeToString,
      ),
      'GetCliente': grpc.unary_unary_rpc_method_handler(
          servicer.GetCliente,
          request_deserializer=chat__pb2.idCliente.FromString,
          response_serializer=chat__pb2.Cliente.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat.Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
